### PR TITLE
fix: explorer perfs issues

### LINKED ISSUE #2121: [BUG] Horrible search performances in food2 processes explorer
## Explication du bug / Bug Explanation

With the growing number of food2 processes added, the [explorer search](https://ecobalyse.beta.gouv.fr/#/explore/food2) performances are getting barely unusable. We should investigate why, and provide a fix.

## Comportement attendu / Expected Behavior

Search should be snappier, or at least usable.

### PR DESCRIPTION
**Pull request by vjousse**
## :wrench: Problem

Fixes https://github.com/MTES-MCT/ecobalyse/issues/2121

Searching processes in the explorer is very slow, especially for `food2` where there are a lot of processes in the DB.

## :cake: Solution

Compute the word indexation once when loading the DB and don’t encode the CSV for every keystroke, do it only when downloading the file.

## :desert_island: How to test

Open the https://ecobalyse-staging-pr2154.osc-fr1.scalingo.io/#/explore/food2 URL and try to search for terms, the display should be a lot faster than what we currently have here https://ecobalyse.beta.gouv.fr/#/explore/food2

Downloading the corresponding CSV should work the same as before.

### CODE REVIEW

File: src/Data/Text.elm [hunk 1]
```diff
@@ -40,8 +40,10 @@ search { minQueryLength, query, toString } elements =
                 searchWords
                     |> List.all
                         (\word ->
-                            fn (String.toLower word) <|
-                                toWords (toString element)
+                            fn word <|
+                                (element
+                                    |> toSearchableWords
+                                )
```
Comment (n1k0) [inline src/Data/Text.elm]:
```suggestion
                            element
                                |> toSearchableWords
                                |> fn word
```

File: src/Data/Process.elm [hunk 2]
```diff
@@ -280,6 +288,13 @@ toSearchableString process =
         ]
 
 
+toSearchableWords : Process -> List String
+toSearchableWords process =
+    process
+        |> toSearchableString
+        |> Text.toWords
```
Comment (n1k0) [inline src/Data/Process.elm]:
```suggestion
toSearchableWords =
    toSearchableString >> Text.toWords
```

File: src/Page/Explore.elm [hunk 3]
```diff
@@ -135,6 +138,9 @@ update session msg model =
                         |> Nav.pushUrl session.navKey
                     ]
 
+        DownloadCsv filename csv ->
+            createPageUpdate session model |> App.withCmds [ Download.string filename "text/csv" (csv |> EncodeCsv.toString) ]
```
Comment (n1k0) [inline src/Page/Explore.elm]:
```suggestion
        DownloadCsv filename csv ->
            createPageUpdate session model
                |> App.withCmds [ Download.string filename "text/csv" (csv |> EncodeCsv.toString) ]
```

File: src/Page/Explore.elm [hunk 4]
```diff
@@ -303,7 +309,7 @@ countriesExplorer :
 countriesExplorer { distances, countries } tableConfig tableState scope maybeCode =
     [ countries
         |> List.filter (.scopes >> List.member scope)
-        |> Table.viewList OpenDetail tableConfig tableState scope (ExploreCountries.table distances countries)
+        |> Table.viewList OpenDetail DownloadCsv tableConfig tableState scope (ExploreCountries.table distances countries)
```
Comment (n1k0) [inline src/Page/Explore.elm]: the `DownloadCsv` message should be part of the passed `Config` (here `tableConfig`). Sample patch:

```diff
diff --git i/src/Page/Explore.elm w/src/Page/Explore.elm
index d4ba4f2be..5341ab103 100644
--- i/src/Page/Explore.elm
+++ w/src/Page/Explore.elm
@@ -309,7 +309,7 @@ countriesExplorer :
 countriesExplorer { distances, countries } tableConfig tableState scope maybeCode =
     [ countries
         |> List.filter (.scopes >> List.member scope)
-        |> Table.viewList OpenDetail DownloadCsv tableConfig tableState scope (ExploreCountries.table distances countries)
+        |> Table.viewList OpenDetail tableConfig tableState scope (ExploreCountries.table distances countries)
     , case maybeCode of
         Just code ->
             detailsModal
@@ -337,7 +337,7 @@ impactsExplorer :
 impactsExplorer definitions tableConfig tableState scope maybeTrigram =
     [ Definition.toList definitions
         |> List.sortBy (.trigram >> Definition.toString)
-        |> Table.viewList OpenDetail DownloadCsv tableConfig tableState scope ExploreImpacts.table
+        |> Table.viewList OpenDetail tableConfig tableState scope ExploreImpacts.table
     , maybeTrigram
         |> Maybe.map (\trigram -> Definition.get trigram definitions)
         |> Maybe.map (Table.viewDetails scope ExploreImpacts.table)
@@ -382,7 +382,7 @@ foodExamplesExplorer db tableConfig tableState maybeId =
     [ scoredExamples
         |> List.filter (Tuple.first >> .query >> (/=) FoodQuery.empty)
         |> List.sortBy (Tuple.first >> .name)
-        |> Table.viewList OpenDetail DownloadCsv tableConfig tableState Scope.Food (FoodExamples.table max)
+        |> Table.viewList OpenDetail tableConfig tableState Scope.Food (FoodExamples.table max)
     , case maybeId of
         Just id ->
             detailsModal
@@ -414,7 +414,7 @@ foodIngredientsExplorer :
 foodIngredientsExplorer { food } tableConfig tableState maybeId =
     [ food.ingredients
         |> List.sortBy .name
-        |> Table.viewList OpenDetail DownloadCsv tableConfig tableState Scope.Food FoodIngredients.table
+        |> Table.viewList OpenDetail tableConfig tableState Scope.Food FoodIngredients.table
     , case maybeId of
         Just id ->
             detailsModal
@@ -451,7 +451,7 @@ processesExplorer session scope tableConfig tableState maybeId =
     in
     [ scopedProcesses
         |> List.sortBy Process.getDisplayName
-        |> Table.viewList OpenDetail DownloadCsv tableConfig tableState scope (Processes.table session)
+        |> Table.viewList OpenDetail tableConfig tableState scope (Processes.table session)
     , case maybeId of
         Just id ->
             detailsModal
@@ -483,7 +483,7 @@ componentsExplorer session scope tableConfig tableState maybeId =
     in
     [ scopedComponents
         |> List.sortBy .name
-        |> Table.viewList OpenDetail DownloadCsv tableConfig tableState scope (Components.table session)
+        |> Table.viewList OpenDetail tableConfig tableState scope (Components.table session)
     , case maybeId of
         Just id ->
             detailsModal
@@ -527,7 +527,7 @@ objectExamplesExplorer session tableConfig tableState scope maybeId =
     [ scoredExamples
         |> List.filter (Tuple.first >> .query >> (/=) Component.emptyQuery)
         |> List.sortBy (Tuple.first >> .name)
-        |> Table.viewList OpenDetail DownloadCsv tableConfig tableState scope (ObjectExamples.table max)
+        |> Table.viewList OpenDetail tableConfig tableState scope (ObjectExamples.table max)
     , case maybeId of
         Just id ->
             detailsModal
@@ -580,7 +580,7 @@ textileExamplesExplorer session tableConfig tableState maybeId =
     in
     [ scoredExamples
         |> List.sortBy (Tuple.first >> .name)
-        |> Table.viewList OpenDetail DownloadCsv tableConfig tableState Scope.Textile (TextileExamples.table session max)
+        |> Table.viewList OpenDetail tableConfig tableState Scope.Textile (TextileExamples.table session max)
     , case maybeId of
         Just id ->
             detailsModal
@@ -611,7 +611,7 @@ textileProductsExplorer :
     -> List (Html Msg)
 textileProductsExplorer session tableConfig tableState maybeId =
     [ session.db.textile.products
-        |> Table.viewList OpenDetail DownloadCsv tableConfig tableState Scope.Textile (TextileProducts.table session)
+        |> Table.viewList OpenDetail tableConfig tableState Scope.Textile (TextileProducts.table session)
     , case maybeId of
         Just id ->
             detailsModal
@@ -636,7 +636,7 @@ textileMaterialsExplorer :
     -> List (Html Msg)
 textileMaterialsExplorer db tableConfig tableState maybeId =
     [ db.textile.materials
-        |> Table.viewList OpenDetail DownloadCsv tableConfig tableState Scope.Textile (TextileMaterials.table db)
+        |> Table.viewList OpenDetail tableConfig tableState Scope.Textile (TextileMaterials.table db)
     , case maybeId of
         Just id ->
             detailsModal
@@ -731,6 +731,7 @@ exploreView ({ db } as session) { facetValues, scope, dataset, tableState, searc
                 { defaultCustomizations
                     | tableAttrs = [ class "table table-striped table-hover mb-0 view-list cursor-pointer" ]
                 }
+            , downloadCsv = DownloadCsv
             }
     in
     case dataset of
diff --git i/src/Page/Explore/Table.elm w/src/Page/Explore/Table.elm
index ac573debe..d7770c4ff 100644
--- i/src/Page/Explore/Table.elm
+++ w/src/Page/Explore/Table.elm
@@ -67,6 +67,7 @@ type alias Config data msg =
     , onFacetToggle : String -> String -> Bool -> msg
     , columns : List (SortableTable.Column data msg)
     , customizations : SortableTable.Customizations data msg
+    , downloadCsv : String -> Csv -> msg
     , selectedFacets : Facets
     , search : String
     }
@@ -100,14 +101,13 @@ viewDetails scope createTable item =
 
 viewList :
     (Route -> msg)
-    -> (String -> Csv -> msg)
     -> Config data msg
     -> SortableTable.State
     -> Scope
     -> ({ detailed : Bool, scope : Scope } -> Table data comparable msg)
     -> List data
     -> Html msg
-viewList routeToMsg csvDownloadMsg defaultConfig tableState scope createTable items =
+viewList routeToMsg defaultConfig tableState scope createTable items =
     let
         ({ filename, toId, toRoute, toSearchableWords, facets, columns, legend } as table) =
             createTable { detailed = False, scope = scope }
@@ -204,7 +204,7 @@ viewList routeToMsg csvDownloadMsg defaultConfig tableState scope createTable it
                 , div [ class "text-end pt-3" ]
                     [ button
                         [ class "btn btn-secondary"
-                        , onClick <| csvDownloadMsg csv.filename csv.content
+                        , onClick <| defaultConfig.downloadCsv csv.filename csv.content
                         ]
                         [ text "Télécharger ces données au format CSV" ]
                     ]

```

**Review by n1k0 — APPROVED** [review]
Perfs are much better! I feel there's still some rendering lag on the large food2 processes list, but the situation is so much better than previously that I want this to land fast 😄
