### PR TITLE
fix: add 500km of road transport for default FR

### LINKED ISSUE #1975: (Transport) Mettre en cohérence les distances depuis la "France" et "(par défaut) France"
### :wrench: Problème

- pour un même pays, qui est par défaut et non par défaut, on obtient pas les mêmes valeurs
Par exemple: Si je sélectionne Abricot FR alors la localisation est '(par défaut) France', soit 160km de camion
Si je modifie la localisation de Abricot FR, pour 'France', alors les distances sont 160km de camion + 500km de camion.
La bonne valeur est la dernière.

:cake: Solution

:rotating_light: Points d'attention/commentaires

:desert_island: Comment tester

Voir les tests dans l'epic #1983 

:pencil: Description de l’évolution

### PR DESCRIPTION
**Pull request by vjousse**
fixes https://github.com/MTES-MCT/ecobalyse/issues/1975

### CODE REVIEW

File: src/Data/Food/Recipe.elm [hunk 1]
```diff
@@ -429,7 +429,15 @@ computeIngredientTransport db { country, ingredient, mass, planeTransport } =
                         Transport.addRoadWithCooling (Length.kilometers 500) (ingredient.transportCooling == Ingredient.AlwaysCool) t
 
                     else
-                        t
+                        -- If it’s coming « Par défaut » from France, we add 500 km of road to simulate the same behavior than when the data
+                        -- is coming from the `transports.json` file
```
Comment (n1k0) [inline src/Data/Food/Recipe.elm]:
```suggestion
                        -- If coming "from France by default", add 500 km of road to simulate the same behavior than when the data
                        -- is coming from the `transports.json` file
```

File: src/Data/Food/Recipe.elm [hunk 2]
```diff
@@ -429,7 +429,15 @@ computeIngredientTransport db { country, ingredient, mass, planeTransport } =
...
+                        -- This corresponds to the stage "3. RECETTE" in the
+                        -- [transport documentation](https://fabrique-numerique.gitbook.io/ecobalyse/alimentaire/transport#circuits-consideres)
+                        -- https://github.com/MTES-MCT/ecobalyse/issues/1975
+                        Transport.addRoadWithCooling
+                            (Length.kilometers 500)
+                            (ingredient.transportCooling == Ingredient.AlwaysCool || ingredient.transportCooling == Ingredient.CoolOnceTransformed)
+                            t
```
Comment (n1k0) [inline src/Data/Food/Recipe.elm]:
```suggestion
                        Transport.addRoadWithCooling (Length.kilometers 500)
                            (List.member ingredient.transportCooling [ Ingredient.AlwaysCool, Ingredient.CoolOnceTransformed ])
                            t
```

Comment (n1k0) [reply src/Data/Food/Recipe.elm]: I'd even go as far as putting `List.member ingredient.transportCooling [ Ingredient.AlwaysCool, Ingredient.CoolOnceTransformed ]` in some dedicated `Ingredient.isTransportedCooled` helper

**Review by n1k0 — APPROVED** [review]
LGTM with optional nits

**Comment by PDagras** [comment]
Vérification faite. Le comportement attendu est bien le bon 👌
