### PR TITLE
fix(api): expose server fqdn and version to urls in responses

### LINKED ISSUE #1360: Add the version to the webUrl result field in the textile API
## :wrench: Problem

[Feedback de carbonfact](https://chat.ecobalyse.fr/ecobalyse/pl/5gtj3ymeopf3dnpyk5o4upywga):

> Bonjour,
>
>J'ai une question concernant les résultats renvoyés par la route /textile/simulator, et plus précisément le champ webUrl. Serait-il possible que l'URL renvoyée inclue la version de l'API ?
Actuellement, le champ webUrl redirige toujours vers la version la plus récente de l'API, même si la simulation a été générée avec une version plus ancienne. Cela peut prêter à confusion lors de la comparaison des résultats, car le score affiché via le lien peut différer de celui enregistré dans la charge utile d'origine.
>
>Bien cordialement.

### PR DESCRIPTION
**Pull request by ccomb**
## :wrench: Problem

The `webUrl` returned by the API is hardcoded to `ecobalyse.beta.gouv.fr`, even when running on the staging or a review app:

```
{
  "webUrl": "https://ecobalyse.beta.gouv.fr/........
```

Also, when using a versioned API, it doesn't contain the version, making the resulting scores in the web version possibly differing from the ones in the API response. Note: this patch takes over #1363 in this regard and fixes #1360

## :cake: Solution

Instead of a harcoded FQDN, use the host transmitted from the request. Also reflect the version used for the API in the Web urls.

## :desert_island: How to test

Check in the API, when running a request, that you get the right FQDN:

Example on this PR:
```
{
  "webUrl": "https://ecobalyse-staging-pr1381.osc-fr1.scalingo.io#/food/ecs/ey.....
```

With versioned APIs, check that the version is preserved in the web urls as well.

image

### CODE REVIEW

**Review by n1k0 — APPROVED** [review]

File: server.js [hunk 1]
```diff
@@ -320,16 +323,30 @@ version.all(
...
       processes: versionProcesses,
       jsResponseHandler: ({ status, body }) => {
-        respondWithFormattedJSON(res, status, body);
+        respondWithFormattedJSON(res, status, ensureVersionedUrls(body, versionNumber));
       },
     });
   },
 );
 
+// Add version number to web urls (done here to avoid reverse patching old static version builds)
```
Comment (vjousse) [inline server.js:339]: ❤️
